### ISSUE TITLE
MsigDB Ontology gene sets missing

### ISSUE THREAD

**Issue by pcantalupo** [huayc09/SeuratExtend#12]
Hello, 
I'm looking for the C5 Ontology gene sets https://www.gsea-msigdb.org/gsea/msigdb/human/genesets.jsp?collection=C5 but cannot find them in your Genesets_data
![image](https://github.com/user-attachments/assets/bd275f24-4e03-4561-8029-4db1d045b940)

```
> names(SeuratExtendData::Genesets_data$mouse$GSEA)
 [1] "positional gene sets"                 "all curated gene sets"               
 [3] "chemical and genetic perturbations"   "BioCarta gene sets"                  
 [5] "KEGG gene sets"                       "PID gene sets"                       
 [7] "all canonical pathways"               "all motif gene sets"                 
 [9] "transcription factor targets"         "all computational gene sets"         
[11] "all immunologic signatures gene sets" "hallmark gene sets" 
```

Am I missing something?  Thank you

**Comment by huayc09** [comment]
Thank you for bringing this to my attention. The C5 Ontology gene sets you're looking for aren't stored in the `Genesets_data` object, but are instead contained in a separate `GO_Data` object. Here's how you can access them:

For human GO ID to gene list mappings:
```R
GO_Data$human$GO2Gene
```

For mouse:
```R
GO_Data$mouse$GO2Gene
```

Additionally, SeuratExtend includes the complete Reactome database in the `Reactome_Data` object, accessible similarly:
```R
Reactome_Data$human$Path2Gene
```

Both `GO_Data` and `Reactome_Data` also store full hierarchy information (e.g., parent-child relationships between pathways) using the "ontology_index" class, which you can explore further.

SeuratExtend provides several helper functions to easily extract needed information. For example, to get all Biological Process (BP, GO:0008150) pathway IDs from the GO database:
```R
go_terms <- FilterGOTerms(parent = "GO:0008150", spe = "human")
```

The following returns a list of pathway ID to gene list mappings:
```R
GO_Data$human$GO2Gene[go_terms]
```

The `RenameGO` function can convert pathway IDs back to pathway names.

If you need more assistance or would like to learn about additional tips and tricks, please let me know!

**Comment by pcantalupo** [comment]
Hello
Thank you for the info.  Is `GO_Data` documented anywhere? I cannot find it in the docs nor in R with `data(package = "SeuratExtend")`

```
Data sets in package 'SeuratExtend':
PanglaoDB_data                 
hall50                         
human_ensembl_genesymbol       
mouse_ensembl_genesymbol       
mouse_human_genesymbols        
pbmc                           
presets_color_iwh              
presets_color_pro              
```

How do I get the ~7000 GO gene sets for BP like in the above picture?  I cannot figure out how to do this with `FilterGOTerms` nor by looking into the `GO_Data` object. The [docs](https://huayc09.github.io/SeuratExtend/articles/GSEA.html#filter-the-goreactome-pathway-list-based-on-certain-criteria) do not describe it as well.   Maybe I'm missing something very simple which is usally the case

Thank you

**Comment by huayc09** [comment]
I understand your confusion. Let me clarify:

The `GO_Data`, `Genesets_data`, and other databases are actually part of the `SeuratExtendData` package. By default, `SeuratExtendData` is attached when you load `SeuratExtend`. I moved these databases to a separate package because they're quite large (>50MB), and I didn't want users to have to download them every time `SeuratExtend` is updated.

Regarding the Human MSigDB Collections' C5: ontology gene sets you mentioned, I checked and it seems to be downloaded from https://amigo.geneontology.org/amigo/, containing 7608 gene sets for BP. The `GO_Data` in my package is downloaded from the official GO website (https://geneontology.org/) and includes >16000 pathways for BP, so it's more comprehensive. MSigDB Collections might have filtered these pathways, though I'm not sure of their criteria. Also, MSigDB Collections' pathway naming differs from GO's official naming.

While `GO_Data` itself isn't documented, its usage is integrated into the `GeneSetAnalysisGO()` and related functions. You can find more information here: https://huayc09.github.io/SeuratExtend/articles/GSEA.html#gene-ontology-go-database

If you want to calculate GSEA, using `GeneSetAnalysisGO` is recommended as it has powerful filtering capabilities. To calculate all BP pathways, you can use:

```R
pbmc <- GeneSetAnalysisGO(pbmc, root = "BP", spe = "human", nCores = 4)
```

Then you can extract the AUCell score matrix for further analysis, as shown in the tutorial. Note that calculating all BP pathways may be time-consuming.

If you prefer to extract pathway-gene lists for custom analysis without using `GeneSetAnalysis` functions, you can get this information from `GO_Data$human$GO2Gene` and use `RenameGO` to restore pathway names.

If you still want to use the 7000 GO BP gene sets from MSigDB Collections' C5, you can download the GMT format file (e.g., from https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/2024.1.Hs/c5.go.bp.v2024.1.Hs.symbols.gmt) and process it using relevant package functions (like `getGmt()` from the `GSEABase` package).

I hope this helps clarify things. Let me know if you have any more questions.

**Comment by pcantalupo** [comment]
That makes sense...thank you for your help.
