### ISSUE TITLE
Question about waterfall plot

### ISSUE THREAD

**Issue by ccruizm** [huayc09/SeuratExtend#14]
Good day! This is a great package. I started using it, but when I use `WaterfallPlot,` I get some bars colored dark grey. I just updated the package to the latest version, and now got even worse. See below. What do you think the issue is? 

Before update:
![CleanShot 2024-10-18 at 15 25 35@2x](https://github.com/user-attachments/assets/f42c380f-80fd-4a7b-a341-f7f45014900b)

After update (v1.0.4):
![CleanShot 2024-10-18 at 15 27 03@2x](https://github.com/user-attachments/assets/7d416b9b-2024-47fe-97ce-4915c303c514)

Thanks in advance!

**Comment by huayc09** [comment]
Thank you for your feedback. I appreciate you bringing this issue to my attention. The problem you're experiencing is due to extremely significant statistical test results (in this case, from t-tests) where p-values approach zero so closely that -log10(p) becomes infinitely large (Inf), causing display issues and resulting in grey bars.
I've observed that the `t.test` function in R can calculate p-values down to approximately 1e-325, beyond which it cannot compute accurately.
To address this, I've implemented a patch in version 1.0.5 that sets an upper limit of 325 for -log10(p). This ensures that even when p-values are too small to calculate, we avoid Inf values, allowing the plot to display normally. While this solution isn't perfect, it's a practical compromise.
Given that you have many bars exceeding the 325 threshold, you might not see much color gradient. An alternative approach would be to use the t-score instead of -log10(p) for coloring. You can do this by setting `color = "tscore"` in the function call, which should better display the differences.
Please try updating to the latest version and see if it resolves the issue. If you're still experiencing problems or have any questions, don't hesitate to reach out!

**Comment by ccruizm** [comment]
Thanks @huayc09 for the speedy reply and fix! I confirm it works nicely! 

Once again, great tool!
