### ISSUE TITLE
`DimPlot2` is not showing any dots

### ISSUE THREAD

**Issue by h4rvey-g** [huayc09/SeuratExtend#17]
Hi! I'm using `DimPlot2` on my Seurat data
```R
r$> sc_opt
An object of class Seurat 
44806 features across 505629 samples within 1 assay 
Active assay: RNA (44806 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 4 dimensional reductions calculated: pca, umap_on_pca, scvi, umap
```
```R
p <- DimPlot2(sc_opt, features = "RNA_snn_res.0.2", reduction = "umap", label = TRUE)
ggsave("temp.png", p, width = 10, height = 10)
```
But the result image is not showing any dots
![image](https://github.com/user-attachments/assets/79e2e3dd-0d99-4ca0-b735-d37a2e875a14)
I tried to plot on `pbmc` data and it works well. I don't understand why it's not working on my data.

**Comment by huayc09** [comment]
Thank you for your question. The issue occurs because your dataset has over 100,000 cells (505,629 samples), which automatically triggers `raster = TRUE`. While rasterization is beneficial for handling large datasets as it converts the UMAP into an image format rather than plotting hundreds of thousands of individual points (preventing huge vector files like PDFs), the default `pt.size` behaves differently in raster mode.

You can try either of these solutions:

```R
# Solution 1: Increase point size with raster mode
p <- DimPlot2(sc_opt, 
              features = "RNA_snn_res.0.2", 
              reduction = "umap", 
              label = TRUE,
              pt.size = 0.1)  # or try larger values like 1

# Solution 2: Disable raster mode (warning: may create large files)
p <- DimPlot2(sc_opt, 
              features = "RNA_snn_res.0.2", 
              reduction = "umap", 
              label = TRUE,
              raster = FALSE)
```

I apologize for any confusion this may have caused. While manual adjustment of `pt.size` is needed for now, I plan to address this issue in an upcoming update to prevent the invisible points problem when `raster = TRUE` is automatically triggered for datasets over 100,000 cells.

Feel free to let me know if you need any further assistance or if the points are still not visible after adjusting these parameters.

**Comment by h4rvey-g** [comment]
Thanks! Setting `pt.size = 1` works.
By the way, I've noticed that setting `pt.size = 0.1` will create a plot with very faint color. Is that normal?
![image](https://github.com/user-attachments/assets/ae617049-2d33-4b24-8cdc-81d483ac2a20)
`pt.size = 1` works well.
![image](https://github.com/user-attachments/assets/9546cffc-91fa-4ca3-8c18-2529349d792e)

**Comment by huayc09** [comment]
I am happy to know it works! Yes, it's normal that `pt.size = 0.1` creates a plot with very faint colors. This happens because when using raster mode, each pixel's color is essentially an average between the point color and the white background. When points are very small (like 0.1), the white background dominates the average, resulting in faint colors.

This is why `pt.size = 1` works better - it gives the points enough size to maintain their color intensity in the rasterized image. I recommend sticking with `pt.size = 1` for the best visualization of your data when using raster mode.

Thank you for your feedback, it helps us understand how to better guide other users who might encounter similar situations!
