### ISSUE TITLE
Adding a title to FeaturePlot3()

### ISSUE THREAD

**Issue by BenDo85** [huayc09/SeuratExtend#18]
Hi, I'm trying to add a title to FeaturePlot3() but it seems I'm not able to do it

Here's some example code of what I'm trying to do:
``FeaturePlot3(pbmc, "Car4", "Clic5", "Jup") + ggtitle("My title")``

Also, thanks for this awesome package!

**Comment by huayc09** [comment]
Thanks for using SeuratExtend! Since the plot is created using `ggarrange` to combine the main plot with the legend, regular `ggtitle()` won't work directly. However, you can add a title using `annotate_figure()` from the ggpubr package after creating the plot:

```R
p <- FeaturePlot3(pbmc, "CD3D", "CD68", "CD79A")
annotate_figure(p, top = text_grob("My title", face = "bold", size = 14))
```

You can customize the title appearance by modifying the `text_grob()` parameters:
- `size`: control text size
- `face`: "plain", "bold", "italic", or "bold.italic"
- `color`: change text color
- `family`: specify font family

Let me know if you need help with any other customizations!

**Comment by BenDo85** [comment]
Works like a charm!

Thank you very much for your time and your quick reply!
