### ISSUE TITLE
why the heatmap with feature_text_subset  not show the gene name

### ISSUE THREAD

**Issue by honghh2018** [huayc09/SeuratExtend#6]
Hi developer,
    I want to plot the  heatmap with specific genes name ,but it can not show properly 
    the code lying below:
 toplot2 <- CalcStats(obj, features = unique(topN$gene), method = "zscore", order = "p")

    p1 <- Heatmap(toplot2, lab_fill = "zscore", feature_text_subset = specific_genes, expand_limits_x = c(-0.5, 11))
    # ggsave(p1, filename = paste0(outdir, '/heatmap5.pdf'), width = 15, height = 15)
    # ggsave(p1, filename = paste0(outdir, '/heatmap5.png'), width = 15, height = 15)

    ggsave(p1, filename = paste0(outdir, '/', paste0('heatmap5_', marker_type_origin, '.png')), width = 25, height = 15)
    ggsave(p1, filename = paste0(outdir, '/', paste0('heatmap5_', marker_type_origin, '.pdf')), width = 25, height = 15)
    
    the picture show like that:
    not show the gene name
![image](https://github.com/user-attachments/assets/1f003b90-bbac-4301-916c-1b61a72b34f9)

Any advices would be appreciated
Best,
hanhuihong

**Comment by huayc09** [comment]
Thank you for your question. To address the issue of gene names not showing properly in your heatmap, you can try the following adjustments:

1. Increase the right boundary of the heatmap. For example, change the 11 in your code to 15 (you may need to experiment to find the most suitable value):

```R
p1 <- Heatmap(toplot2, lab_fill = "zscore", feature_text_subset = specific_genes, expand_limits_x = c(-0.5, 15))
```

Or more concisely, if you don't need to adjust the left boundary:

```R
p1 <- Heatmap(toplot2, lab_fill = "zscore", feature_text_subset = specific_genes, expand_limits_x = 15)
```

2. Since your cluster names appear to be short, I suggest setting the x-axis text angle to 0. This eliminates the need for a 45-degree angle to save space:

```R
p1 <- Heatmap(toplot2, lab_fill = "zscore", feature_text_subset = specific_genes, expand_limits_x = 15, angle = 0, hjust = 0.5)
```

3. Regarding the `ggsave` function, I recommend reducing the `width` and `height` values for a more aesthetically pleasing result. With the current large dimensions, the text might appear too small relative to the overall image size, making it difficult to read.

I hope these suggestions help improve the visibility of your gene names and the overall appearance of your heatmap.

**Comment by honghh2018** [comment]
Thanks the urge reply, i would be replot my data soon and wish it well
Best,
